# Generated by Django 3.1.7 on 2021-03-28 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='input',
            name='sequence',
        ),
        migrations.AddField(
            model_name='input',
            name='combo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='combos.combo'),
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
    ]
